FROM node:16.4.0-alpine

ARG MONGO_URL
ARG ACCESS_TOKEN_SECRET
ARG REFRESH_TOKEN_SECRET

ENV MONGO_URL=$MONGO_URL
ENV ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
ENV REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY src/ src/
COPY swagger.json ./

USER node

CMD [ "npm", "start" ]

EXPOSE 8000