name: Develop Pipeline
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
      - run: npm install