name: Develop Pipeline
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  install:
    env:
      CI: true
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
    strategy:
      matrix:
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'

      - name: Npm install
        run: npm install
      
      - name: Run tests
        env:
          MONGO_URL: ${{ secrets.MONGO_URL_TEST }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
        run: npm run test
